---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
  push:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'

jobs:
  Compile-Indicator:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    strategy:
      matrix:
        file:
          - Misc/TMA+CG_mladen_NRP_Histogram
          - PriceBands/TMA+CG_mladen_NRP
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          ref: v3.000.1
          repository: EA31337/EA31337-classes
      - name: Compile required indicator for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2361
          path: indicators-other/${{ matrix.file }}.mq4
          verbose: true
      - name: Compile required indicator for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2515
          path: indicators-other/${{ matrix.file }}.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Indicators
          path: '**/*.ex[45]'
  Compile-Strategy:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          ref: v3.000.1
          repository: EA31337/EA31337-classes
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2361
          path: Stg_TMA_CG.mq4
          verbose: true
      - name: Compile strategy for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2515
          path: Stg_TMA_CG.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EA
          path: '*.ex[45]'
